platform: linux/arm

clone:
  git:
    image: quay.io/armswarm/drone-git

pipeline:
  prepare:
    image: quay.io/armswarm/alpine:3.7
    environment:
      - ALPINE_VERSION=3.7
      - DOCKER_VERSION=17.10.0-ce
      - DOCKER_PACKAGE=17.10.0-r0
      - DIND_COMMIT=3b5fac462d21ca164b3778647420016315289034
    commands:
      - |-
          sed -i \
            -e "s/{{DOCKER_VERSION}}/$${DOCKER_VERSION}/" \
            -e "s/{{DOCKER_PACKAGE}}/$${DOCKER_PACKAGE}/" \
            -e "s/{{DIND_COMMIT}}/$${DIND_COMMIT}/" \
            -e "s/{{ALPINE_VERSION}}/$${ALPINE_VERSION}/" \
            Dockerfile dind/Dockerfile

  build_and_publish_docker_image:
    image: quay.io/armswarm/drone-docker
    secrets: [ docker_username, docker_password, docker_registry ]
    repo: quay.io/armswarm/docker
    tag: [ "17.10.0-ce", "17.10.0", "17.10", "17", "latest", "edge" ]
    when:
      branch: master
      event: push

  build_and_publish_dind_image:
    image: quay.io/armswarm/drone-docker
    secrets: [ docker_username, docker_password, docker_registry ]
    repo: quay.io/armswarm/docker
    context: dind/
    dockerfile: dind/Dockerfile
    tag: [ "17.10.0-ce-dind", "17.10.0-dind", "17.10-dind", "17-dind", "dind", "edge-dind" ]
    when:
      branch: master
      event: push

  notify:
    image: quay.io/armswarm/drone-slack
    secrets: [ slack_webhook, plugin_channel, plugin_template ]
    when:
      status: [ failure, success ]
