pipeline:
  prepare:
    image: quay.io/armswarm/alpine:3.5
    environment:
      - ALPINE_VERSION=3.5
      - DOCKER_VERSION=17.05.0-ce
      - DIND_COMMIT=3b5fac462d21ca164b3778647420016315289034
    commands:
      - |-
          sed -i \
            -e "s/{{DOCKER_VERSION}}/${DOCKER_VERSION}/" \
            -e "s/{{DIND_COMMIT}}/${DIND_COMMIT}/" \
            -e "s/{{ALPINE_VERSION}}/${ALPINE_VERSION}/" \
            Dockerfile dind/Dockerfile

  build-docker:
    image: armswarmdrone/docker
    repo: quay.io/armswarm/docker
    tag: [ "17.05.0-ce", "17.05.0", "17.05", "17", "latest", "edge" ]
    when:
      branch: master
      event: push

  build-dind:
    image: armswarmdrone/docker
    repo: quay.io/armswarm/docker
    context: dind/
    tag: [ "17.05.0-ce-dind", "17.05.0-dind", "17.05-dind", "17-dind", "dind", "edge-dind" ]
    when:
      branch: master
      event: push

  slack:
    when:
      status: [ failure, success ]
